//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComisionOperacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComisionOperacion()
        {
            this.ComisionEmpleadoes = new HashSet<ComisionEmpleado>();
        }
    
        public int Id { get; set; }
        public int ComisionVentaId { get; set; }
        public decimal monto { get; set; }
    
        public virtual ComisionVenta ComisionVenta { get; set; }
        public virtual Operacion Operacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComisionEmpleado> ComisionEmpleadoes { get; set; }
    }
}
