//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRetencion
    {
        public int Id { get; set; }
        public decimal monto { get; set; }
        public int FacturaId { get; set; }
        public int RetencionId { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Retencion Retencion { get; set; }
    }
}
