//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
        }

        public Empresa(int id, string nombre, string ruc)
        {
            Id = id;
            this.nombre = nombre;
            this.ruc = ruc;
        }

        public Empresa(int id, string nombre, string ruc, Representante representante) : this(id, nombre, ruc)
        {
            Representante = representante;
        }

        public int Id { get; set; }
        public string nombre { get; set; }
        public string ruc { get; set; }
    
        public virtual Representante Representante { get; set; }
    }
}
