//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public string metodo { get; set; }
        public int CobroId { get; set; }
    
        public virtual Cobro Cobro { get; set; }
    }
}
