//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante : Persona
    {
        public Representante()
        {
        }

        public Representante(int id, string nombre1, string nombre2, string apellido1, string apellido2, string cedula, string pais, string correo, string telefono) : base(id, nombre1, nombre2, apellido1, apellido2, cedula, pais, correo, telefono)
        {
        }

        public virtual Empresa Empresa { get; set; }
    }
}
