//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGECOContainer : DbContext
    {
        public SIGECOContainer()
            : base("name=SIGECOContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<DetalleRetencion> DetalleRetencions { get; set; }
        public virtual DbSet<Retencion> Retencions { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<ComisionEmpleado> ComisionEmpleadoes { get; set; }
        public virtual DbSet<Cobro> Cobroes { get; set; }
        public virtual DbSet<Pago> Pagoes { get; set; }
        public virtual DbSet<ComisionVenta> ComisionVentas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<ComisionOperacion> ComisionOperacions { get; set; }
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Rango> Rangoes { get; set; }
        public virtual DbSet<PagoEmpleado> PagoEmpleadoes { get; set; }
    }
}
