//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id { get; set; }
        public string tipo { get; set; }
    
        public virtual ComisionVenta ComisionVenta { get; set; }
        public virtual Cobro Cobro { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
